### ISSUE TITLE
GHDL simulation v1.0 regression

### ISSUE THREAD

**Issue by jiegec** [SpinalHDL/SpinalHDL#414] opened 2021-05-04 14:49 UTC
As discussed in https://github.com/SpinalHDL/SpinalHDL/pull/412#issuecomment-831882384, there is a regression in simulation:

Run `testOnly spinal.tester.scalatest.Axi4CrossbarTesterCocotbBoot` in sbt:

- GHDL 0.36-dev (Debian 0.35+git20181129+dfsg-3) [Dunoon edition]: Completes 
- GHDL 1.0.0 (Debian 1.0.0+dfsg-1) [Dunoon edition]: Never completes

**Comment by Yuwenfeng2019** [comment] 2021-05-04 16:22
Thanks!
I used the Fedora Spin 33 XFCE on my Raspberry Pi, and is using the GHDL 1.0dev Dunnon edition:
![image](https://user-images.githubusercontent.com/48667051/117034805-3db45600-ad36-11eb-97ca-8d5993898504.png)
It seems that the blocked cases may caused by the latest GHDL version, but as GHDL is mainly written in Ada, it is difficult to debug.
If these issues are really caused by GHDL version, then the test result on X86 should have the similar phenomenon when testing with GHDL 1.0?

**Comment by Dolu1990** [comment] 2021-05-12 11:49
@SomeParticles Hi ^^
This issue may concern you.

**Comment by bellaz89** [comment] 2021-05-12 12:27
Hi, could you also verify if this behavior is present with all the three GHDL backend? (mcode, LLVM, GCC) Thanks!

**Comment by bellaz89** [comment] 2021-05-12 12:34
@Dolu1990 Are we sure that this is a problem of the SpinalHDL GHDL backend? 
Doesn't  spinal.tester.scalatest.Axi4CrossbarTesterCocotbBoot use Cocotb? In this case that would mean that there is some problem with Cocotb GHDL backend.

**Comment by Dolu1990** [comment] 2021-05-12 18:26
@bellaz89 @SomeParticles 
I'm sorry, i was reading it as "there is a issue in the SpinalHDL based simulation" :/

> Doesn't spinal.tester.scalatest.Axi4CrossbarTesterCocotbBoot use Cocotb?

Right

> In this case that would mean that there is some problem with Cocotb GHDL backend.

Right, and it already happend by the past, that's why i realy tried to fix versions to working one in travis to avoid wasting people time on transiants.

So i would say, let's wait a bit.

**Comment by typingArtist** [comment] 2021-06-21 15:07
This problem exists on Fedora 34 as well.
```
$ ghdl --version
GHDL 1.0-dev () [Dunoon edition]
 Compiled with GNAT Version: 11.0.0 20210210 (Red Hat 11.0.0-
 GCC back-end code generator
Written by Tristan Gingold.

Copyright (C) 2003 - 2020 Tristan Gingold.
GHDL is free software, covered by the GNU General Public License.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Dolu1990** [comment] 2021-06-22 11:55
So, a easy way to reproduce the issue is to run StreamTester2CocotbBoot

basicaly, there, the VHDL statement "fifoAPop_valid <= fifoA_io_pop_valid;" isn't properly applied by the simulation and instead, fifoAPop_valid is set to zero all the time while fifoA_io_pop_valid is having some fun XD

Not sure if that's a pure GHDL issue, or if things get corrupted via cocotb / VPI / GHDL

**Comment by typingArtist** [comment] 2021-06-23 23:37
Found the problem. See SpinalHDL/cocotblib#10. It seems that GHDL 1.0 takes driving an output from the outside serious, so when you drive it LOW in the Cocotb monitor and then ask for the value of the output signal, you actually get a static LOW indication. Previously, you still got the DUT output signal.

**Comment by typingArtist** [comment] 2021-06-24 13:21
@jiegec  I think that with the latest fix and merge, the regression is gone and we can close the issue.

**Closed** 2021-06-24 13:44 UTC
