### ISSUE TITLE
SimConfig.withWave changes the behavior

### ISSUE THREAD

**Issue by piegamesde** [SpinalHDL/SpinalHDL#607] opened 2022-02-09 11:26 UTC
It is not the first time it happens to me, but last time I was unsure about my sanity. Basically, when I have a debugging issue and set `withWave` or `withFstWave` to get a trace of what's happening, the behavior of the hardware changes. This time, I'm debugging what I suspect to be a boot loop, and when I set the flag I instead get an instant failure with:

```
FAILURE DBusSimplePlugin doesn't allow memory stage stall when read happend
[Error] Simulation failed at time=1416661
Exception in thread "main" spinal.sim.SimFailure: Verilog assertion failure
	at spinal.sim.SimManager.runWhile(SimManager.scala:284)
	at spinal.sim.SimManager.run(SimManager.scala:227)
	at spinal.core.sim.SimCompiled.doSimApi(SimBootstraps.scala:433)
	at spinal.core.sim.SimCompiled.doSim(SimBootstraps.scala:393)
```

>

**Comment by dnltz** [comment] 2022-02-09 19:55
I can confirm this assertion failure. Additionally to the posted trace, I also had a `failed at time=0`.

Issue is related to VexRiscv and not SpinalHDL: https://github.com/SpinalHDL/VexRiscv/blob/77e361e91e93b5d292f795106e6981f5897818e8/src/main/scala/vexriscv/plugin/DBusSimplePlugin.scala#L523

**Comment by piegamesde** [comment] 2022-02-09 20:58
@dnltz Can you also confirm that `withWave` is causing/surfacing this?

**Comment by dnltz** [comment] 2022-02-10 07:55
@piegamesde well, I do not run tests without wave generation. I'll remove this parameter and run some tests in a loop.

**Comment by Dolu1990** [comment] 2022-02-10 10:31
Hi, i think that's verilator which initialise things in some random way, and that random way is the withWave.

Then that assert trigger due to bad reset handeling by the simuation environnement

To be honnest i think those assert can be removed.

**Comment by piegamesde** [comment] 2022-02-16 15:30
I ran again into a case where setting `withWave` changed the behavior. This time however, the code *doesn't* work without the flag. I'll try to minimize it.

**Comment by Dolu1990** [comment] 2022-02-17 15:25
One thing, with verilator, if you enable or disable the FST/VCD trace, then the dut will have different random initial values.

**Comment by piegamesde** [comment] 2022-03-03 14:55
How are those random initializations seeded? Do they use the simulation seed or are they completely random? Because my issue has been rather consistent over the last few weeks, and one would assume that if it was caused by random noise that it would be a lot less deterministic.

**Comment by Dolu1990** [comment] 2022-03-04 09:33
it isn't a seeding issue, it is that verilator do not generate the same stuff if you ask it to get the wave or not.

The workaround that behaviour is to always do withWave, but disable the capture at the start of the sim : 
enableSimWave

About Vex, those assertion can be removed.

**Comment by piegamesde** [comment] 2022-03-07 16:50
@dnltz

```scala
        val clockDomain = ClockDomain(dut.io.clk, dut.io.reset)
        clockDomain.forkStimulus(mainClkPeriod)
```

I could not find any other lines w.r.t. clock/release handling in the simulation code. Therefore, the clock domain should be using the default settings (async reset, reset on high, clock on rising edge)

**Comment by dnltz** [comment] 2022-03-07 19:30
@piegamesde - Ah yes, maybe it's worth trying to trigger the reset after some nanoseconds.

Sometimes I miss the X values from Xilinx's simulator. These random values are nice, but you actually do not know if a reset is missing/not working.

**Comment by piegamesde** [comment] 2022-03-07 20:07
> Sometimes I miss the X values from Xilinx's simulator.

Yes. Or the 0x0a0a0a0a0a default values from BlueSpec.

**Comment by dnltz** [comment] 2022-03-08 08:57
@piegamesde Can you share some Verilog code? AFAIK the simulation dumps it somewhere. `simWorkspace` in my project.

**Comment by Dolu1990** [comment] 2022-03-09 10:44
@dnltz 
> Sometimes I miss the X values from Xilinx's simulator. These random values are nice, but you actually do not know if a reset is missing/not working.

I pushed a fix about it a few months ago : 
https://github.com/SpinalHDL/SpinalHDL/commit/1c78f2e9ebccf4a1969e11b9c2bcfc9ffcca70ae

Now this should be good

**Comment by numero-744** [comment] 2022-10-23 22:32
Hi!

Please, can anyone confirm it is fixed?

**Comment by numero-744** [comment] 2022-11-15 13:44
No answer, I close it as fixed

**Closed by numero-744** 2022-11-15 13:44 UTC
Labels: bug :bug:, done? :white_check_mark:
