### ISSUE TITLE
sbt compile failed

### ISSUE THREAD

**Issue by balanx** [SpinalHDL/SpinalHDL#922] opened 2022-10-22 09:27 UTC
I downloaded the latest sources, and got the following error information.

```
D:\msys64\home\Administrator\SpinalHDL-dev>sbt
[info] welcome to sbt 1.7.1 (Oracle Corporation Java 18)
[info] loading settings for project spinalhdl-dev-build from plugin.sbt ...
[info] loading project definition from D:\msys64\home\Administrator\SpinalHDL-dev\project
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.jsuereth:sbt-pgp:1.1.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.eed3si9n:sbt-unidoc:0.4.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.eed3si9n:sbt-assembly:0.14.10 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.jsuereth:sbt-pgp;sbtVersion=1.0;scalaVersion=2.12:1.1.0
[error]   Not found
[error]   Not found
[error]   not found: D:\.sbt\.ivy2\localcom.jsuereth\sbt-pgp\scala_2.12\sbt_1.0\1.1.0\ivys\ivy.xml
[error]   not found: https://repo.huaweicloud.com/repository/maven/com/jsuereth/sbt-pgp_2.12_1.0/1.1.0/sbt-pgp-1.1.0.po
[error]   not found: https://repo1.maven.org/maven2/com/jsuereth/sbt-pgp_2.12_1.0/1.1.0/sbt-pgp-1.1.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/1.1.0/ivys/artifact.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/jsuereth/sbt-pgp_2.12_1.0/1.1.0/sbt-pgp-1.1.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/jsuereth/sbt-pgp_2.12_1.0/1.1.0/sbt-pgp-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.jsuereth/sbt-pgp/1.1.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.jsuereth/sbt-pgp/1.1.0/ivys/ivy.xml
[error] Error downloading com.eed3si9n:sbt-unidoc;sbtVersion=1.0;scalaVersion=2.12:0.4.1
[error]   Not found
[error]   Not found
```

**Comment by Readon** [comment] 2022-10-22 09:43
I just tried on my existing environment, there is no problem.

Someone report that "sbt-pgp" package has been renamed recently. 
I am not familiar with the distribution policy of sbt and java world, but that might be a problem for new user without existing working environment.

**Comment by numero-744** [comment] 2022-10-22 10:58
```
% sbt
[info] welcome to sbt 1.6.0 (N/A Java 17.0.4.1)
```

I wonder if it can be linked to `sbt` version. @Readon what version of sbt do you have?

**Comment by Readon** [comment] 2022-10-22 11:02
1.6.0 on Ubuntu 20 & 1.5.5 on Windows
Both works well.

**Comment by Readon** [comment] 2022-10-22 11:04
It had to be tried in a new, clean environment, but I didn't have one on hand.

**Comment by numero-744** [comment] 2022-10-22 11:05
Do you think the issue is can be that 1.7.1 is too recent?

I'll try to dockerize a new clean environment to check with 1.7.1.

**Comment by Readon** [comment] 2022-10-22 11:15
On my Windows, there are only pacakge files on "...\Coursier\cache\v1\https\repo.scala-sbt.org\scalasbt\sbt-plugin-releases\com.jsuereth\sbt-pgp\scala_2.12\sbt_1.0\1.1.0"
I think use coursier to install the sbt might helps.

**Comment by balanx** [comment] 2022-10-22 12:46
I changed to sbt-1.6.0 and  there is still the same error information.

**Comment by balanx** [comment] 2022-10-22 12:46
I changed to sbt-1.6.0 and  there is still the same error information.

**Comment by Readon** [comment] 2022-10-22 12:47
> I changed to sbt-1.6.0 and there is still the same error information.

Would you please try to install sbt with coursier first?

**Comment by balanx** [comment] 2022-10-22 12:52
Sorry, I am not familiar with  coursier. May you give me some guide information more ?

**Comment by Readon** [comment] 2022-10-22 13:08
This [link](https://get-coursier.io/docs/sbt-coursier) might helps.

**Comment by Dolu1990** [comment] 2022-10-24 09:58
You may had some bad-luck where some online server were offline ?
Is the issue still perssisting ?

**Comment by Dolu1990** [comment] 2022-10-24 10:08
I updated the sbt-pgp depedency.
@balanx It may be fine now ?

**Comment by balanx** [comment] 2022-10-24 10:43
There is another error information.
```
PS D:\msys64\home\WIN10\SpinalHDL-dev> sbt
[info] welcome to sbt 1.6.2 (Oracle Corporation Java 18)
[info] loading settings for project spinalhdl-dev-build from plugin.sbt ...
[info] loading project definition from D:\msys64\home\WIN10\SpinalHDL-dev\project
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.eed3si9n:sbt-unidoc:0.4.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.eed3si9n:sbt-assembly:0.14.10 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.eed3si9n:sbt-unidoc;sbtVersion=1.0;scalaVersion=2.12:0.4.1
[error]   Not found
[error]   Not found
[error]   not found: D:\.sbt\.ivy2\localcom.eed3si9n\sbt-unidoc\scala_2.12\sbt_1.0\0.4.1\ivys\ivy.xml
[error]   not found: https://repo.huaweicloud.com/repository/maven/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://maven.aliyun.com/repository/public/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://maven.aliyun.com/repository/central/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo1.maven.org/maven2/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-unidoc/scala_2.12/sbt_1.0/0.4.1/ivys/artifact.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/eed3si9n/sbt-unidoc_2.12_1.0/0.4.1/sbt-unidoc-0.4.1.pom
```

**Comment by Dolu1990** [comment] 2022-10-24 11:17
@balanx Ahhh, i just pushed another update for  sbt-unidoc, it may be fine now, if not, let's me know :)

**Comment by balanx** [comment] 2022-10-24 14:08
Ahhh :)
com.eed3si9n:sbt-assembly:2.0.0

```
[info] welcome to sbt 1.6.2 (Oracle Corporation Java 18)
[info] loading settings for project spinalhdl-dev-build from plugin.sbt ...
[info] loading project definition from D:\msys64\home\WIN10\SpinalHDL-dev\project
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.eed3si9n:sbt-assembly:0.14.10 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.eed3si9n:sbt-assembly;sbtVersion=1.0;scalaVersion=2.12:0.14.10
[error]   Not found
[error]   Not found
[error]   not found: D:\.sbt\.ivy2\localcom.eed3si9n\sbt-assembly\scala_2.12\sbt_1.0\0.14.10\ivys\ivy.xml
[error]   not found: https://repo.huaweicloud.com/repository/maven/com/eed3si9n/sbt-assembly_2.12_1.0/0.14.10/sbt-assembly-0.14.10.pom
[error]   not found: https://maven.aliyun.com/repository/public/com/eed3si9n/sbt-assembly_2.12_1.0/0.14.10/sbt-assembly-0.14.10.pom
[error]   not found: https://maven.aliyun.com/repository/central/com/eed3si9n/sbt-assembly_2.12_1.0/0.14.10/sbt-assembly-0.14.10.pom
```

**Comment by balanx** [comment] 2022-10-25 14:06
com.eed3si9n:sbt-assembly:1.1.0
There is NO error after modifying it like above

**Comment by Dolu1990** [comment] 2022-10-25 17:28
@numero-744 @balanx Thanks :D

**Comment by Dolu1990** [comment] 2022-10-25 17:54
Merged

**Closed** 2022-10-25 17:53 UTC
Labels: done? :white_check_mark:, question :recycle:
