### ISSUE TITLE
[VCS API] When I use VCS as a backend for emulation, it seems to have problems with Z-state warnings and VCS API does not seem to support oneFilePerComponent config

### ISSUE THREAD

**Issue by AlenLqx** [SpinalHDL/SpinalHDL#829] opened 2022-08-21 06:51 UTC
Hi， I encountered some error when do VCS simulation，Please take a look. Thank you.

1）Z-State Warning
Take a simple adder as an example：
![(TWA67AQ3HV~A372UIOLV2X](https://user-images.githubusercontent.com/84823360/185778834-d946699a-2692-457e-b116-6274fa6a8b95.png)
Its running results are as follows：
![)XPSKVD5}JC9ACH{(HO@TFS](https://user-images.githubusercontent.com/84823360/185778888-6034e96e-fdab-48b6-ba3a-75af55933aef.png)
It seems to give a Z-state warning that shouldn't be there
2）oneFilePerComponent
Use the following code to simulate：
![FXWP LEC$QBGD1YPDMHFQJH](https://user-images.githubusercontent.com/84823360/185779238-313f8a12-7169-4ba3-a533-3ffbc2b92ca4.png)
I encountered this error after running：
![@4}KY7 M_@@5 {FS_96 Q8C](https://user-images.githubusercontent.com/84823360/185779293-7d4e281c-291b-4e61-8437-ebb15cc1132c.png)

**Comment by Dolu1990** [comment] 2022-08-22 08:27
Hi :)

To send the code in text format you can do : 

\`\`\`scala
Your code here
\`\`\`

It make things easier for us to reproduce.

Also which version of VCS do you have ?

**Comment by Charles-Lqx** [comment] 2022-08-22 09:48
Okay.

1) In the Z-State warning case, the example as follow:

/* scala code */
import spinal.lib._
import spinal.core._
import spinal.core.sim._

import scala.util.Random._

case class Demo() extends Component {
  val io = new Bundle {
    val a     = in UInt (8 bits)
    val b     = in UInt (8 bits)
    val ret = out UInt (9 bits)
  }

  io.ret := RegNext(io.a +^ io.b).init(U(0))
}
object demoTest extends App {
  SimConfig.withVCS(VCSFlags(elaborateFlags = List("-LDFLAGS -Wl,--no-as-needed")))
    .withFSDBWave.workspacePath(s"./simWorkSpace").allOptimisation.compile(Demo()).doSim { dut =>
    dut.io.a #= 0
    dut.io.b #= 0
    dut.clockDomain.forkStimulus(10)
    dut.io.a #= nextInt(256)
    dut.io.b #= nextInt(256)
    dut.clockDomain.waitSampling(2)
  }
}

/*end */

it's run window output log is :

/* output */

[Progress] VCS compilation started.
[Progress] VCS user environment setup.
[VLOGAN] vlogan -nc -full64 -sverilog +v2k -ntb -debug_access+all -timescale=1ns/1ps -l vlogan.log  /home/charles/IdeaProjects/SpGears/tmp/job_1/Demo.v ./rtl/__simulation_def.v
[VCS] vcs -full64 -quiet -timescale=1ns/1ps -debug_access+all -debug_acc+pp+dmptf -debug_region=+cell+encrypt -l vcs.log +vpi +vcs+initreg+random -load /home/charles/IdeaProjects/SpGears/./simWorkspace/.pluginsCachePath/vpi_vcs.so:entry_point_cb -o Demo -P /opt/synopsys/verdi201809/share/PLI/VCS/LINUX64/novas.tab /opt/synopsys/verdi201809/share/PLI/VCS/LINUX64/pli.a -LDFLAGS -Wl,--no-as-needed Demo __simulation_def
[Progress] VCS compilation done in 3.730 s
[SIMV] ./Demo 
Chronologic VCS simulator copyright 1991-2018
Contains Synopsys proprietary information.
Compiler version O-2018.09-SP2_Full64; Runtime version O-2018.09-SP2_Full64;  Aug 22 17:37 2022
Shared memory key : SpinalHDL_0_1_1944201789_-1021641580_1661161054087_-7132551111646221440
Start of simulation
*Verdi* Loading libsscore_vcs201809.so
FSDB Dumper for VCS, Release Verdi_O-2018.09-SP2, Linux x86_64/64bit, 02/21/2019
(C) 1996 - 2019 by Synopsys, Inc.
*Verdi* : Create FSDB file 'Demo.fsdb'
*Verdi* : Begin traversing the scope (Demo), layer (0).
*Verdi* : End of traversing.
*Verdi* : Flush all FSDB Files at 0 ps.
[Progress] Start Demo test simulation with seed 76217937
Warning, value 'z' at position 0 is neither '0' or '1'. value set to '0'.
Warning, value 'z' at position 0 is neither '0' or '1'. value set to '0'.
Unexpected termination of the simulation
           V C S   S i m u l a t i o n   R e p o r t 
Time: 180 ps
CPU Time:      0.340 seconds;       Data structure size:   8.0Mb
Mon Aug 22 17:37:34 2022
[Done] Simulation done in 53.592 ms

/* end */

It seems to give a Z-state warning that shouldn't be there. Because both inputs have initial values.

2) In the oneFilePerComponent case, the example as follow:

/* scala code */

import spinal.lib._
import spinal.core._
import spinal.core.sim._

import scala.util.Random._

case class DemoCounter() extends Component {
  val cOut = out UInt(4 bits)
  cOut := CounterFreeRun(16)
}
case class Demo() extends Component {
  val io = new Bundle {
    val a     = in UInt (8 bits)
    val b     = in UInt (8 bits)
    val ret = out UInt (9 bits)
    val counterOut = out UInt(4 bits)
  }

  io.ret := RegNext(io.a +^ io.b).init(U(0))
  val counter = DemoCounter()
  io.counterOut := counter.cOut
}
object demoTest extends App {
  SimConfig.withVCS(VCSFlags(elaborateFlags = List("-LDFLAGS -Wl,--no-as-needed")))
    .withConfig(SpinalConfig(oneFilePerComponent = true))
    .withFSDBWave.workspacePath(s"./simWorkSpace").allOptimisation.compile(Demo()).doSim { dut =>
    dut.io.a #= 0
    dut.io.b #= 0
    dut.clockDomain.forkStimulus(10)
    dut.io.a #= nextInt(256)
    dut.io.b #= nextInt(256)
    dut.clockDomain.waitSampling(2)
  }
}

/* end */

I encountered this error after running in this case ：

the log is : 

/* output log */

[Progress] VCS compilation started.
[Progress] VCS user environment setup.
[VLOGAN] vlogan -nc -full64 -sverilog +v2k -ntb -debug_access+all -timescale=1ns/1ps -l vlogan.log  /home/charles/IdeaProjects/SpGears/tmp/job_1/Demo.v ./rtl/__simulation_def.v
[VCS] vcs -full64 -quiet -timescale=1ns/1ps -debug_access+all -debug_acc+pp+dmptf -debug_region=+cell+encrypt -l vcs.log +vpi +vcs+initreg+random -load /home/charles/IdeaProjects/SpGears/./simWorkspace/.pluginsCachePath/vpi_vcs.so:entry_point_cb -o Demo -P /opt/synopsys/verdi201809/share/PLI/VCS/LINUX64/novas.tab /opt/synopsys/verdi201809/share/PLI/VCS/LINUX64/pli.a -LDFLAGS -Wl,--no-as-needed Demo __simulation_def
Doing common elaboration Warning-[DBGACC_REG] Unrecognized '-debug_region' option  Option '' is not a valid '-debug_region' option.  Please recompile using the '-debug_access<+options>' switch and incremental   options as required.  Recommended options are '-debug_access' for   post-process debug, '-debug_access+class' for testbench debug, and   '-debug_access+all' for all debug capabilities.  Refer the VCS user guide   for more granular options for debug control under the switch '-debug_access'  and refer to '-debug_region' for region control.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_register_cb' is not supported in the compiler.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_chk_error' is not supported in the compiler.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_chk_error' is not supported in the compiler.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_register_cb' is not supported in the compiler.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_chk_error' is not supported in the compiler.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_chk_error' is not supported in the compiler.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_register_cb' is not supported in the compiler.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_chk_error' is not supported in the compiler.Warning-[VPI-CT-NS] VPI function is not supported  The VPI function 'vpi_chk_error' is not supported in the compiler.Error-[URMI] Unresolved modules/home/charles/IdeaProjects/SpGears/tmp/job_1/Demo.v, 18"DemoCounter counter( .cOut (counter_cOut[3:0]),  .clk (clk),  .reset (reset));"  Module definition of above instance is not found in the design.10 warnings1 error common elaboration failed
Exception in thread "main" java.lang.Exception: Elaboration of Demo failed
	at spinal.sim.VpiBackend.doCmd(VpiBackend.scala:82)
	at spinal.sim.VCSBackend.elaborate$1(VpiBackend.scala:778)
	at spinal.sim.VCSBackend.analyzeRTL(VpiBackend.scala:790)
	at spinal.sim.VpiBackend.delayed_compilation$lzycompute(VpiBackend.scala:159)
	at spinal.sim.VpiBackend.delayed_compilation(VpiBackend.scala:108)
	at spinal.sim.VpiBackend.instanciate_(VpiBackend.scala:172)
	at spinal.sim.VpiBackend.instanciate(VpiBackend.scala:195)
	at spinal.sim.VpiBackend.instanciate(VpiBackend.scala:207)
	at spinal.sim.SimVpi.<init>(SimVpi.scala:15)
	at spinal.core.sim.SpinalSimConfig$$anon$7.newSimRaw(SimBootstraps.scala:985)
	at spinal.core.sim.SimCompiled.doSimApi(SimBootstraps.scala:521)
	at spinal.core.sim.SimCompiled.doSim(SimBootstraps.scala:498)
	at SpGears.Other.demoTest$.delayedEndpoint$SpGears$Other$demoTest$1(SpinalHDLTest.scala:28)
	at SpGears.Other.demoTest$delayedInit$body.apply(SpinalHDLTest.scala:25)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at SpGears.Other.demoTest$.main(SpinalHDLTest.scala:25)
	at SpGears.Other.demoTest.main(SpinalHDLTest.scala)

/* end */

3) My VCS version information is : 

vcs script version : O-2018.09
machine name = fpga-eda 
machine type = linux64 
machine os = Linux 5.15.0-43-generic  
The FLEXlm host ID of this machine is "000c29238993"
Compiler version = VCS-MX O-2018.09-SP2_Full64


Thank you for your reply!

**Comment by Dolu1990** [comment] 2022-08-23 06:57
Notification to @wswslzp @jijingg  :)

**Comment by Charles-Lqx** [comment] 2022-08-24 15:40
Ok! Thank you! I will continue to wait for the first question reply.

**Comment by numero-744** [comment] 2022-10-03 19:10
Hello, any updates for this issue?

**Comment by wswslzp** [comment] 2022-10-04 08:00
Hi all, sorry for my late update. I've been quite busy during this time. 

The second one should be fixed by #882 .

**Comment by numero-744** [comment] 2022-10-04 13:12
Great! What about the Z-value warnings?

**Comment by Dolu1990** [comment] 2022-10-05 09:14
Ahh the Z warnings are due to the clock domain sampling being done at the same delta cycle than the forkStimulus is done,
I pushed a fix.

So everything should be fixed now ^^

**Comment by AlenLqx** [comment] 2022-10-05 09:31
Great！Thanks.

**Closed** 2022-10-05 09:31 UTC

**Comment by Alen302** [comment] 2023-08-08 13:24
hello! @Dolu1990 , Regarding the repair of the Z state problem of the VCS, you seem to have forgotten to merge into the new version :
https://github.com/SpinalHDL/SpinalHDL/issues/829
