### ISSUE TITLE
ConcurrentModificationException with nested switch

### ISSUE THREAD

**Issue by ronan-lashermes** [SpinalHDL/SpinalHDL#588] opened 2022-01-19 16:59 UTC
Hi,
I run into an elaboration exception when using nested switch, on v1.6.1. I cannot find if this is a bug or a mistake on my part.

## Minimal reproducing example

```scala
package debug

import spinal.core._

class Debug() extends Component {
    val io = new Bundle {
        val in1 = in(UInt(5 bits))
        val in2 = in(UInt(5 bits))
        val out1 = out(UInt(5 bits))
    }

    val out_reg = Reg(UInt(5 bits)) init 0
    io.out1 := out_reg

    switch(io.in1) {
        is(1) {
            switch(io.in2) {
                is(1) {
                    out_reg := 1
                }
            }
        }
    }
}
```

return upon elaboration (you need to build the component somewhere with **val dbg = new Debug()**)
```
[info] [Warning] Elaboration failed (0 error).
[info]           Spinal will restart with scala trace to help you to find the problem.
[info] **********************************************************************************************
[info] [Progress] at 0.365 : Elaborate components
[info] [Progress] at 0.383 : Checks and transforms
[error] Exception in thread "main" java.util.ConcurrentModificationException: mutation occurred during iteration
[error] 	at scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
[error] 	at scala.collection.mutable.CheckedIndexedSeqView$CheckedIterator.hasNext(CheckedIndexedSeqView.scala:47)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error] 	at spinal.core.internals.SwitchStatement.$anonfun$normalizeInputs$1(Statement.scala:457)
[error] 	at spinal.core.internals.SwitchStatement.$anonfun$normalizeInputs$1$adapted(Statement.scala:457)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error] 	at spinal.core.internals.SwitchStatement.bitVectorNormalize$1(Statement.scala:457)
[error] 	at spinal.core.internals.SwitchStatement.normalizeInputs(Statement.scala:508)
[error] 	at spinal.core.internals.PhaseNormalizeNodeInputs.$anonfun$impl$112(Phase.scala:1327)
[error] 	at spinal.core.internals.PhaseNormalizeNodeInputs.$anonfun$impl$112$adapted(Phase.scala:1323)
[error] 	at spinal.core.internals.ScopeStatement.$anonfun$walkStatements$1(Statement.scala:150)
[error] 	at spinal.core.internals.ScopeStatement.$anonfun$walkStatements$1$adapted(Statement.scala:148)
[error] 	at spinal.core.internals.ScopeStatement.foreachStatements(Statement.scala:143)
[error] 	at spinal.core.internals.ScopeStatement.walkStatements(Statement.scala:148)
[error] 	at spinal.core.internals.PhaseContext.$anonfun$walkStatements$1(Phase.scala:129)
[error] 	at spinal.core.internals.PhaseContext.$anonfun$walkStatements$1$adapted(Phase.scala:129)
[error] 	at spinal.core.internals.GraphUtils$.walkAllComponents(Misc.scala:268)
[error] 	at spinal.core.internals.GraphUtils$.$anonfun$walkAllComponents$1(Misc.scala:269)
[error] 	at spinal.core.internals.GraphUtils$.$anonfun$walkAllComponents$1$adapted(Misc.scala:269)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error] 	at spinal.core.internals.GraphUtils$.walkAllComponents(Misc.scala:269)
[error] 	at spinal.core.internals.GraphUtils$.$anonfun$walkAllComponents$1(Misc.scala:269)
[error] 	at spinal.core.internals.GraphUtils$.$anonfun$walkAllComponents$1$adapted(Misc.scala:269)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error] 	at spinal.core.internals.GraphUtils$.walkAllComponents(Misc.scala:269)
[error] 	at spinal.core.internals.PhaseContext.walkStatements(Phase.scala:129)
[error] 	at spinal.core.internals.PhaseNormalizeNodeInputs.impl(Phase.scala:1323)
[error] 	at spinal.core.internals.PhaseContext.doPhase(Phase.scala:181)
[error] 	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12(Phase.scala:2564)
[error] 	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12$adapted(Phase.scala:2562)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error] 	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$7(Phase.scala:2562)
[error] 	at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:66)
[error] 	at spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2499)
[error] 	at spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2494)
[error] 	at spinal.core.Spinal$.apply(Spinal.scala:371)
[error] 	at spinal.core.SpinalConfig.generateVerilog(Spinal.scala:164)
[error] 	at spinal.core.sim.SpinalSimConfig.compileCloned(SimBootstraps.scala:633)
[error] 	at spinal.core.sim.SpinalSimConfig.compile(SimBootstraps.scala:617)
[error] 	at spinal.core.sim.SpinalSimConfig.doSim(SimBootstraps.scala:608)

```
Notice that the logically equivalent example below with a nested *when* instead of a nested *switch* does not raise any error.
```scala
package debug

import spinal.core._

class Debug() extends Component {
    val io = new Bundle {
        val in1 = in(UInt(5 bits))
        val in2 = in(UInt(5 bits))
        val out1 = out(UInt(5 bits))
    }

    val out_reg = Reg(UInt(5 bits)) init 0
    io.out1 := out_reg

    when(io.in1 === 1) {
           when(io.in2 === 1) {
               out_reg := 1
           }
    }
}
```
Isn’t it possible to nest switch statements ? Of course I could cheat in this case and switch on *in1 ## in2*, but my inputs are actually enums...

**Comment by Dolu1990** [comment] 2022-01-22 23:31
Hi

I just tried, but can't reproduce the crash. Do you have a full project example with the bug ?

**Comment by ronan-lashermes** [comment] 2022-01-25 12:53
Ok, I investigated a bit more to pin the incriminating factor and I found it: the error appears when using Scala 2.13.7. When setting scala version to 2.11.12 (from the Sbt template), everything works fine.

**Comment by ronan-lashermes** [comment] 2022-01-25 13:41
Added a repo with the reproducible bug [here](https://github.com/ronan-lashermes/SpinalConcurrentModifBug). Changing the scala version in the build.sbt solves the bug.

**Comment by Dolu1990** [comment] 2022-01-25 19:35
Hoo thanks, i will check it.

**Comment by aiit-linry** [comment] 2022-01-27 02:05
so far as I know, scala version up to 2.13.6 works fine, but  2.13.7 has problem

**Comment by Dolu1990** [comment] 2022-01-27 10:08
thanks ^^

**Comment by Dolu1990** [comment] 2022-01-27 10:09
Should be fixed now

**Closed** 2022-01-27 10:08 UTC
