### ISSUE TITLE
VHDL generation does not appear to produce vaild results with Attributes added.

### ISSUE THREAD

**Issue by madscientist42** [SpinalHDL/SpinalHDL#69] opened 2017-07-17 19:49 UTC
From a generator pass of Briey:

> architecture arch of VexRiscv is
> attribute verilator public : boolean;

Here's the complaint from Quartus:

>Error (10500): VHDL syntax error at bt_soc2.vhd(5525) near text "public";  expecting "of"

Another oops from generated VHDL:

> signal writeBack_RegFilePlugin_regFileWrite_valid : std_logic;
> attribute verilator public of writeBack_RegFilePlugin_regFileWrite_valid: signal is true;

...and the complaint from Quartus:

> Error (10500): VHDL syntax error at bt_soc2.vhd(5685) near text "public";  expecting "of"

Looks like something's injecting "public" in the mix there and at least Quartus doesn't like it.

**Comment by Dolu1990** [comment] 2017-07-17 20:15
Hooo funny, 
It is not a bug, but just the fact that the "verilator public" attribut used for sim is only for Verilog. I will findout a way to not generate them when the backend is the VHDL one.

**Comment by madscientist42** [comment] 2017-07-17 20:19
Got it.  Misfeature.  X-D

I'll limp along for now in Verilog because at this stage I can get away
with that with this project- I'll just need the "right" thing with VHDL
down the line.  Thanks!

**Comment by Dolu1990** [comment] 2017-07-17 22:10
It's now fixed, you just need to pull the last SpinalHDL version and do a sbt publish-local
I tested it on Quartus 15, it successfuly compile things.

**Closed by Dolu1990** 2017-07-17 22:10 UTC
